/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicagit;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class cargarDatos extends javax.swing.JFrame {
    public static int contadorEstudiantes;
    public static int contadorPrestamos;
    public static int contadorLibros;
    public static int erroresRegistros;
    public static ArrayList <prestamo> listaPrestamo=new ArrayList<prestamo>();
    public static ArrayList <libro> listaLibros=new ArrayList<libro>();
    public static ArrayList <estudiante> listaEstudiantes=new ArrayList<estudiante>();
    ArrayList <prestamo> erroresPrestamo=new ArrayList<prestamo>();
    ArrayList <libro> erroresLibros=new ArrayList<libro>();
    ArrayList <estudiante> erroresEstudiantes=new ArrayList<estudiante>();
    /**
     * Creates new form Principal
     */
    public cargarDatos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargarDatos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarDatos.setText("Cargar  Datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnCargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        String filePath = fc.getSelectedFile().getAbsolutePath();
        System.out.println(filePath);

        BufferedReader reader = null;
        String line = "";
        contadorEstudiantes=0;
        contadorPrestamos=0;
        contadorLibros=0;
        erroresRegistros=0;
        String error="";
        try {
            reader = new BufferedReader(new FileReader(filePath));
            
            while ((line = reader.readLine()) != null) {
                switch (line) {
                    case "LIBRO":
                        
                        String titulo;
                        String autor;
                        String codigo;
                        int copias;
                        line=reader.readLine();
                        String[] atributo = line.split(":");
                        titulo=atributo[1];
                        line=reader.readLine();
                        atributo = line.split(":");
                        autor=atributo[1];
                        line=reader.readLine();
                        atributo = line.split(":");
                        codigo=atributo[1];  
                        line=reader.readLine();
                        atributo = line.split(":");
                        copias=Integer.parseInt(atributo[1]);
                        if (validarFormato(codigo)) {
                            System.out.println("El formato es válido.");
                            listaLibros.add(new libro(titulo, autor, codigo, copias));
                        } else {
                            System.out.println("El formato no es válido.");
                            erroresLibros.add(new libro(titulo, autor, codigo, copias));
                            erroresRegistros++;
                        }
                        reader.readLine();
                        break;
                        
                    case "ESTUDIANTE":
                     
                        int carnet;
                        String nombre;
                        int carrera;
                        line=reader.readLine();
                        atributo = line.split(":");
                        carnet=Integer.parseInt(atributo[1]);
                        line=reader.readLine();
                        atributo = line.split(":");
                        nombre=atributo[1];
                        line=reader.readLine();
                        atributo = line.split(":");
                        carrera=Integer.parseInt(atributo[1]);  
                        
                        if ((carrera==1)||(carrera==2)||(carrera==3)||(carrera==4)||(carrera==5)||(carrera==6)) {
                            System.out.println("El formato es válido.");
                            listaEstudiantes.add(new estudiante(carnet, nombre, carrera));
                        } else {
                            System.out.println("El formato no es válido.");
                            erroresEstudiantes.add(new estudiante(carnet, nombre, carrera));
                            erroresRegistros++;
                        }
                        reader.readLine();
                        break;
                    case "PRESTAMO":
                        String codigoLibro;
                        int carnetEstudiante;
                        String fecha;
                        line=reader.readLine();
                        atributo = line.split(":");
                        codigoLibro=atributo[1];
                        line=reader.readLine();
                        atributo = line.split(":");
                        carnetEstudiante=Integer.parseInt(atributo[1]);
                        line=reader.readLine();
                        atributo = line.split(":");
                        fecha=atributo[1];  
                        
                        if (validarFormatoFecha(fecha)&&validarFormato(codigoLibro)) {
                            System.out.println("El formato es válido.");
                            atributo=fecha.split("-");
                            fecha a = new fecha(Integer.parseInt(atributo[2]),Integer.parseInt(atributo[1]),Integer.parseInt(atributo[0]));
                            listaPrestamo.add(new prestamo(codigoLibro, carnetEstudiante, a));
                        } else {
                            System.out.println("El formato no es válido.");
                            erroresRegistros++;
                        }
                        reader.readLine();
                        break;
                    default:
                        throw new AssertionError();
                }

            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        for (libro a : listaLibros) {
            System.out.println(a.getTitulo());
        }
        JOptionPane.showMessageDialog(null, "se han cargado los datos");
        
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        principal principal = new principal();
        this.setVisible(false);
        principal.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static boolean validarFormato(String input) {
        String regex = "\\d{3}-[A-Za-z]{3}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }
    public static boolean validarFormatoFecha(String input) {
        String regex = "\\d{4}-\\d{2}-\\d{2}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cargarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cargarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
