/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicagit.Reporte;

import com.mycompany.practicagit.Reportes;
import static com.mycompany.practicagit.cargarDatos.listaPrestamo;
import com.mycompany.practicagit.prestamo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ana
 */
public class PrestamoRealizadoEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form PrestamoRealizadoEstudiante
     */
    public PrestamoRealizadoEstudiante() {
        initComponents();
    }
    
    
    public void prestamosHechos(int carnetEstudiante){
        
        String[] prestamoHecho = { "CARNET ESTUDIANTE", "CODIGO DE LIBRO", "FECHA PRESTAMO", "FECHA DEVOLUCION" };
         DefaultTableModel dtm = new DefaultTableModel(null, prestamoHecho);
         for (int i=0; i<listaPrestamo.size(); i++){
             prestamo prestamoHechoEstudiante = listaPrestamo.get(i);
             if(prestamoHechoEstudiante.getCarnetEstudiante()==carnetEstudiante){
                 String[] llenarColumnas=new String [4];
                 llenarColumnas[0]=prestamoHechoEstudiante.getCarnetEstudiante()+"";
                 llenarColumnas[1]=prestamoHechoEstudiante.getCodigoLibro();
                 llenarColumnas[2]=prestamoHechoEstudiante.getFechaPrestamo().toString();
                if (prestamoHechoEstudiante.getFechaDevolucion()== null){
                    llenarColumnas[3]= "el libro aun no ha sido devuelto";
                    
                }else {
                 llenarColumnas[3]=prestamoHechoEstudiante.getFechaDevolucion().toString();
             
                
                }
                    dtm.addRow(llenarColumnas);
             }
             
             
         }
        tabladeprestamoshechos.setModel(dtm);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladeprestamoshechos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        carnetIngresado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        prestamosHechos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladeprestamoshechos.setBackground(new java.awt.Color(255, 255, 255));
        tabladeprestamoshechos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CARNET ESTUDIANTE", "TOTAL DE PRESTAMOS ", "FECHA DE PRESTAMO", "FECHA DEVOLUCION"
            }
        ));
        jScrollPane1.setViewportView(tabladeprestamoshechos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 650, 210));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LISTADO DE PRESTAMOS HECHOS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));
        getContentPane().add(carnetIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 150, -1));

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel2.setText("INGRESE SU CARNET ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        getContentPane().add(prestamosHechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String carnetIngresado = this.carnetIngresado.getText();
                   int ingreso = Integer.valueOf(carnetIngresado);
                   prestamosHechos(ingreso);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Reportes reporteCuatro = new Reportes();
        this.setVisible(false);
        reporteCuatro.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamoRealizadoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamoRealizadoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamoRealizadoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamoRealizadoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestamoRealizadoEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carnetIngresado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel prestamosHechos;
    private javax.swing.JTable tabladeprestamoshechos;
    // End of variables declaration//GEN-END:variables
}
